# Understanding Faiss

In [2]:
#Install Packages
!pip install faiss-cpu
!pip install sentence-transformers

In [3]:
pip install pandas


Note: you may need to restart the kernel to use updated packages.


In [4]:
import pandas as pd


In [5]:
df = pd.read_csv("FAISS_text.csv")

In [6]:
df

text category
0      Meditation and yoga can improve mental health   Health
1  Fruits, whole grains and vegetables helps cont...   Health
2  These are the latest fashion trends for this week  Fashion
3  Vibrant color jeans for male are becoming a trend  Fashion
4                 The concert starts at 7 PM tonight    Event
5  Navaratri dandiya program at Expo center in Mu...    Event
6  Exciting vacation destinations for your next trip   Travel
7  Maldives and Srilanka are gaining popularity i...   Travel

In [7]:
# Converting the text to vector using embeddings 

from sentence_transformers import SentenceTransformer

In [8]:
# Hugging face encoder 
encoder = SentenceTransformer("all-mpnet-base-v2")
vectors = encoder.encode(df.text)

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.6k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/571 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/438M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/363 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

1_Pooling/config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [9]:
vectors

array([[-0.00247389,  0.03626721, -0.0529046 , ..., -0.09152354,
        -0.03970006, -0.04330489],
       [-0.03357259,  0.00980516, -0.03250135, ..., -0.05165474,
         0.02245889, -0.03156186],
       [-0.01865332, -0.04051301, -0.01235387, ...,  0.00610588,
        -0.07179649,  0.02773845],
       ...,
       [-0.0006646 ,  0.04252118, -0.05645503, ...,  0.01315466,
        -0.03183552, -0.04357661],
       [-0.03317149,  0.03252462, -0.0248484 , ...,  0.0117442 ,
         0.05747118,  0.00571022],
       [-0.00166397,  0.00413832, -0.04597079, ...,  0.0200853 ,
         0.05656246, -0.00161593]], dtype=float32)

In [10]:
vectors.shape

(8, 768)

In [11]:
vectors[0]

array([-2.47388566e-03,  3.62672061e-02, -5.29046021e-02, -2.17348374e-02,
        1.41723920e-02, -1.01592776e-03,  2.23637503e-02,  3.65196355e-02,
        3.80901620e-02,  5.22013707e-03, -3.00865863e-02,  2.05451506e-03,
        1.08502386e-02, -8.49088505e-02, -5.57260215e-03, -6.06598035e-02,
        2.32013990e-03, -1.51409060e-02,  1.20671550e-02,  1.98904574e-02,
       -1.27936536e-02, -2.72811763e-02, -3.31878662e-02,  3.40645877e-03,
        8.41168035e-03, -1.94853786e-02,  4.88131978e-02,  2.24119276e-02,
        4.53467295e-02, -5.90892173e-02, -9.13183317e-02, -1.22327334e-03,
       -4.05046493e-02,  8.67175497e-03,  1.26565283e-06, -1.92451999e-02,
       -3.20658721e-02, -4.08172309e-02,  8.79177526e-02, -1.52631681e-02,
        1.09909596e-02, -4.47977781e-02, -4.74827271e-03,  3.52632254e-02,
        1.31071154e-02,  1.09944185e-02, -3.45766451e-03,  9.12349895e-02,
        5.68809435e-02,  4.82893586e-02, -4.51441482e-03,  3.58451083e-02,
       -2.44209487e-02, -

In [12]:
dim = vectors.shape[1]

In [13]:
dim

768

In [14]:
import faiss
index = faiss.IndexFlatL2(dim)

In [15]:
index


<faiss.swigfaiss.IndexFlatL2; proxy of <Swig Object of type 'faiss::IndexFlatL2 *' at 0x17a78c780> >

In [16]:
index.add(vectors)

In [17]:
search_query = "An apple a day keeps doctor away"

In [18]:
vec = encoder.encode(search_query)

In [19]:
vec.shape

(768,)

In [20]:
import numpy as np 
svec = np.array(vec).reshape(1,-1)

In [21]:
svec.shape

(1, 768)

In [22]:
index.search(svec, k=2)

(array([[1.3908098, 1.7193401]], dtype=float32), array([[1, 0]]))

In [23]:
dis, I = index.search(svec, k=2)

In [24]:
dis

array([[1.3908098, 1.7193401]], dtype=float32)

In [25]:
I

array([[1, 0]])

In [26]:
df.loc[I[0]]

text category
1  Fruits, whole grains and vegetables helps cont...   Health
0      Meditation and yoga can improve mental health   Health